### ISSUE TITLE
"Invalid window ID" when using with Vista.vim

### ISSUE THREAD

**Issue by Penaz91** [sunjon/Shade.nvim#19]
Hello. I use [vista.vim](https://github.com/liuchengxu/vista.vim) for symbol lookups and it seems that I can reliably make Shade error by doing the following:

1. Open a document
2. Open Vista (I use the command `:Vista!!` to toggle) - Vista opens correctly
3. Close vista (again I use `:Vista!!`) - Vista hides correctly but the part that was occupied by the side panel is now "Shaded"
4. Open Vista again - I receive an error

The error is the following:

```
Error detected while processing WinEnter Autocommands for "*":                                                                                                       
E5108: Error executing lua /home/penaz/.config/nvim/plugged/shade.nvim/lua/shade.lua:178: Invalid window id: 1003
```

Thank you in advance for your help.

**Comment by sunjon** [comment]
Should be fixed. Please create another issue if it isn't.
