### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by rerrabolu** [sunjon/Shade.nvim#26]
Where does the config element go? Could you please add that to the readme with an example

**Comment by ANGkeith** [comment]
hi, assuming that you're using `neovim`, and `vim-plug`.


```vim
call plug#begin()
" TRUNCATED  ...
Plug 'sunjon/shade.nvim'
" TRUNCATED  ...
call plug#end()

lua require'shade'.setup({
      \   overlay_opacity = 50,
      \   opacity_step = 1,
      \   keys = {
      \     brightness_up    = '<C-Up>',
      \     brightness_down  = '<C-Down>',
      \     toggle           = '<Leader>s',
      \   }
      \ })
```

**Comment by rerrabolu** [comment]
I added the lines you suggested to my .vimrc. Upon launching vim I noticed errors which are included below.

```
user1@RErrabolDevMach:~$ gvim
Error detected while processing /home/user1/.vimrc:
line  141:
[string "vim chunk"]:1: module 'shade' not found:
^Ino field package.preload['shade']
^Ino file '/usr/local/share/lua/5.2/shade.lua'
^Ino file '/usr/local/share/lua/5.2/shade/init.lua'
^Ino file '/usr/local/lib/lua/5.2/shade.lua'
^Ino file '/usr/local/lib/lua/5.2/shade/init.lua'
^Ino file '/usr/share/lua/5.2/shade.lua'
^Ino file '/usr/share/lua/5.2/shade/init.lua'
^Ino file './shade.lua'
^Ino file '/usr/local/lib/lua/5.2/shade.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.2/shade.so'
^Ino file '/usr/lib/lua/5.2/shade.so'
^Ino file '/usr/local/lib/lua/5.2/loadall.so'
^Ino file './shade.so'
user1@RErrabolDevMach:~$
```

I installed python-shade and it didn't seem to make any difference.

**Comment by ANGkeith** [comment]
this is a neovim specific plugin, because it is written in lua.

you're using `gvim` so i don't think you can use this plugin. 

you might want to check out https://github.com/blueyed/vim-diminactive instead. I am not familiar with `gvim`, but the vim-diminactive should be compatible with gvim

**Comment by rerrabolu** [comment]
Thanks for the clarification. I will try in neovim and let you know.

**Comment by sunjon** [comment]
I'm assuming this is resolved now. Create a new issue if you're still having problems.
