### ISSUE TITLE
Shade.nvim doesn't allow for transparent background i.e. `hi Normal guibg=NONE`

### ISSUE THREAD

**Issue by ndavidq0** [sunjon/Shade.nvim#3]
When loading a config one must have a `guibg` color for the `Normal` highlight group.
If it is set to `NONE`: `shade.nvim/lua/shade.lua:119
: bad argument #1 to 'format' (number expected, got nil)`

**Comment by sunjon** [comment]
Should be fixed in https://github.com/sunjon/Shade.nvim/commit/832110cf6fb8b914dbde1365c4b3d2e08ebf96c7
