### ISSUE TITLE
Numbers appear broken

### ISSUE THREAD

**Issue by tamago324** [sunjon/Shade.nvim#5]
- `nvim --version`: NVIM v0.5.0-dev+1256-gd19348923
- Operating system/version: 
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```

- `$TERM`: alacritty
- font: [Cica](https://github.com/miiton/Cica)

### Steps to reproduce

`nvim -u minvimrc -i NONE`

```vim
" minvimrc
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug '~/ghq/github.com/sunjon/Shade.nvim'
call plug#end()

set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

lua << EOF

require'shade'.setup {
  overlay_opacity = 15,
  opacity_step = 1,
  keys = {
    brightness_up = '<C-up>',
    brightness_down = '<C-down>',
    toggle = '<Space>ss',
  },
  -- debug = true,
}

EOF
```

### Actual behaviour

![shade-nvim](https://user-images.githubusercontent.com/16581287/115890161-9c084b80-a48f-11eb-91c4-a9d602cecb55.gif)

### Expected behaviour

I want the numbers to be displayed correctly.
When I set the `width` to `18`, it displays correctly.

https://github.com/sunjon/Shade.nvim/blob/d02c639beecbfe32ee8f813b4c3452033a6fb716/lua/shade.lua#L344

![collect](https://user-images.githubusercontent.com/16581287/115890201-a7f40d80-a48f-11eb-92d1-6feb86a27c60.gif)

Thank you!

**Comment by sunjon** [comment]
Thanks for reporting.
Should be fixed in https://github.com/sunjon/Shade.nvim/commit/0196387bba50b8d36cec99cd6483583ff2dedb42

**Comment by tamago324** [comment]
Thanks!
